// <auto-generated />
using DXAUpdater.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DXAUpdater.Migrations
{
    [DbContext(typeof(UpdatedDataContext))]
    partial class UpdatedDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DXAUpdater.Models.UpdatedData", b =>
                {
                    b.Property<string>("DataID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Active");

                    b.Property<string>("NextDataID");

                    b.Property<string>("Payload");

                    b.Property<string>("PayloadType");

                    b.Property<string>("UpdateDateTimeTicks");

                    b.Property<string>("UpdateDescription");

                    b.Property<string>("UpdatedDomain");

                    b.Property<string>("iUpdatedIdentifiers");

                    b.HasKey("DataID");

                    b.ToTable("UpdatedData");
                });
#pragma warning restore 612, 618
        }
    }
}
